### ISSUE TITLE
The opentaxii-delete-blocks is not working correctly with latest release version(0.1.9).

### ISSUE THREAD

**Issue by nntsugu** [eclecticiq/OpenTAXII#103]
Ref. [`opentaxii-delete-blocks` not deleting records from `collection_to_content_block`](https://github.com/eclecticiq/OpenTAXII/issues/93)

I saw the same situation with 0.1.9 which is latest release version of OpenTaxii.
Its collection_to_content_block's foreign keys are defined without 'ON DELETE CASCADE'.
Ref. https://github.com/eclecticiq/OpenTAXII/blob/0.1.9/opentaxii/persistence/sqldb/models.py#L21-L31

Above problem was resolved on Last Dec.
ref. https://github.com/eclecticiq/OpenTAXII/commit/ad52958d5533cbd23120a7cb7167587938f033ca#diff-ce3f7b939e5c540480ac655aef32c513

But that is not included the latest release(0.1.9).
Because it was released on last June.
So if we install the OpenTaxii by pip, we will meet the same situation when we using the opentaxii-delete-blocks.

Could you make the new release to resolve it?

**Comment by traut** [comment]
new [release 0.1.10](https://github.com/eclecticiq/OpenTAXII/releases/tag/0.1.10) is published.
