### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by mwd102** [eclecticiq/OpenTAXII#104]
Are permissions a new feature? I see they are in the master branch and can be set using https://github.com/eclecticiq/OpenTAXII/blob/master/opentaxii/auth/manager.py but the update_account() method is not present in the latest version in pip.

**Comment by arcsector** [comment]
You have to pull directly from source to get the latest permissions feature. #103 is already open for this specific reason. I think the project might have gone stale, but it still works pretty damn well.

**Comment by mwd102** [comment]
No problem - not really an issue but wanted to clarify. Spent a couple hours figuring out the source on github then thought i was crazy when i went digging through my local copy ;)
