### ISSUE TITLE
Catching erros from app

### ISSUE THREAD

**Issue by ambrous** [eclecticiq/OpenTAXII#105]
Hi!

I am using OpenTAXII of version of 0.1.9 with gunicorn web server.

When an error occurs in my custom api or data converters the error it written to usual log file with other information which I write myself. So I can't set up my monitoring system to detect only error, but not all info from log.

I have following gunicorn start command:

gunicorn opentaxii.http:app --bind localhost:7070 \
--timeout 300 \
--max-requests 100 \
--max-requests-jitter 20 \
--access-logfile /var/log/access-taxii.log \
--error-logfile /var/log/error-taxii.log \
--log-level info

As I understand all errors are catched by middleware by handle_internal_error function to respond xml then, so how can I forward this catched error to error log file as well?

I tried to use default gunicorn config (http://www.opentaxii.org/en/stable/running.html), but had the same case.

Thanks in advance!

**Comment by ambrous** [comment]
@traut thanks a lot for your answer!

Yes, I tried to change logging level in loggin section in our server config, but with any level all logs are written into stdout, including errors as log-line json string (as you mentioned). However I need writing error into stderr.

As I understand, by logging level we can manage what kind of logs we want to see in our log, but can't write error to other log file or stream. Right?

**Comment by traut** [comment]
>  However I need writing error into stderr.
ah, now I see what you mean!

> As I understand, by logging level we can manage what kind of logs we want to see in our log, but can't write error to other log file or stream. Right?

correct. You would have to write/use your own stream handler. This is not something OpenTAXII supports out of the box. I feel you can catch / redirect `error` messages from stdout that gunicorn produces relatively easy though. Maybe with `jq` and some bash magic?

**Comment by ambrous** [comment]
@traut Thanks for your help!

I have had some experiments with gunicorn config, but with unsuccssed result, Then I found  that gunicorn error log ONLY for error within gunicorn server (it was discussed here https://github.com/benoitc/gunicorn/issues/1124).

I just thought that this might be supported out of the box. So it seem to me that I really have to find other way.

So the issue must be closed.

**Comment by traut** [comment]
@ambrous good luck!
