### ISSUE TITLE
Cannot poll feeds from splunk

### ISSUE THREAD

**Issue by zacharycheng** [eclecticiq/OpenTAXII#108]
I am trying to poll data from splunk and here are my configure:
`URL: http://<IP>:9000/services/test_all_poll
POST arguments: collection="test-all-collection" taxii_username="username" taxii_password="password"`

I am sure that the username and the password are correct, but here is what I got back 
`{"exception": "Traceback (most recent call last):\n  File \"/usr/lib64/python2.7/site-packages/flask/app.py\", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/lib64/python2.7/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/usr/lib/python2.7/site-packages/opentaxii/middleware.py\", line 76, in wrapper\n    raise UnauthorizedException()\nUnauthorizedException: UNAUTHORIZED", "level": "warning", "timestamp": "2018-06-12T05:58:33.217832Z", "logger": "opentaxii.middleware", "event": "Status exception"}`

Does anyone know why this would happen? And where can I check the log record? Thanks.

**Comment by arcsector** [comment]
Are you wrapping the opentaxii instance with gunicorn?

**Comment by zacharycheng** [comment]
yes , I am using gunicorn

**Comment by zacharycheng** [comment]
But I only created 1 account in opentaxii conf and it works perfectly in terminal using cabby.
Even if I do not require authentication, I still get the following error 

`{"exception": "Traceback (most recent call last):\n  File \"/usr/lib64/python2.7/site-packages/flask/app.py\", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/lib64/python2.7/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/usr/lib/python2.7/site-packages/opentaxii/middleware.py\", line 85, in wrapper\n    return _process_with_service(service)\n  File \"/usr/lib/python2.7/site-packages/opentaxii/middleware.py\", line 146, in _process_with_service\n    .format(\", \".join((request.accept_mimetypes or []))))\n  File \"/usr/lib/python2.7/site-packages/opentaxii/taxii/exceptions.py\", line 48, in raise_failure\n    tb=tb)\n  File \"<string>\", line 3, in reraise\nFailureStatus: The specified values of Accept is not supported: ", "level": "warning", "timestamp": "2018-06-12T17:19:25.784509Z", "logger": "opentaxii.middleware", "event": "Status exception"}`

**Comment by traut** [comment]
@zacharycheng this:
```
"FailureStatus: The specified values of Accept is not supported: "
```
looks Splunk weirdness -- it seems request didn't have an expected `Accept` header. I'm not familiar with Splunk TAXII client to advice, unfortunately.

**Comment by arcsector** [comment]
Could it be that you have some permissions issues in your collection configuration? The message `FailureStatus: The specified values of Accept is not supported: ` makes me think that your value for `accept_all_content` may be invalid, but @traut would know better than me.

I'm polling from splunk using v0.1.10a1, so it would have to be something that changed with the newest commit...

**Comment by traut** [comment]
> makes me think that your value for `accept_all_content` may be invalid

that's a very good point! thanks, @arcsector.

@zacharycheng could you please check your config?

**Comment by zacharycheng** [comment]
@arcsector @traut right now my inbox is accepting all content. Perhaps let me change to an other inbox which only accepts xml or json to see if it works.

**Comment by zacharycheng** [comment]
The same error is still prompting out after I try to poll from another inbox. Here is my opentaxii config 
`---
services:
  - id: test_all_inbox
    type: inbox
    address: /services/test_all_inbox
    description: Splunk CSV Inbox
    destination_collection_required: yes
    accept_all_content: yes
    authentication_required: no
    protocol_bindings:
      - urn:taxii.mitre.org:protocol:http:1.0

  - id: test_all_discovery
    type: discovery
    address: /services/test_all_discovery
    description: Custom Discovery Service description
    advertised_services:
      - test_all_inbox
      - test_all_discovery
      - test_all_collection_management
      - test_all_poll
    protocol_bindings:
      - urn:taxii.mitre.org:protocol:http:1.0

  - id: test_all_collection_management
    type: collection_management
    address: /services/test_all_collection_management
    description: Custom Collection Management Service description
    protocol_bindings:
      - urn:taxii.mitre.org:protocol:http:1.0

  - id: test_all_poll
    type: poll
    address: /services/test_all_poll
    description: testing poll
    subscription_required: no
    max_result_count: 100
    max_result_size: 10
    authentication_required: no
    protocol_bindings:
      - urn:taxii.mitre.org:protocol:http:1.0

  - id: test_xml_inbox
    type: inbox
    address: /services/test_xml_inbox
    description: Test Splunk Inbox
    destination_collection_required: yes
    accept_all_content: no
    authentication_required: no
    supported_content:
      - urn:stix.mitre.org:xml:1.1.1
    protocol_bindings:
      - urn:taxii.mitre.org:protocol:http:1.0

  - id: test_xml_discovery
    type: discovery
    address: /services/test_xml_discovery
    description: Custom Discovery Service description
    advertised_services:
      - test_xml_inbox
      - test_xml_discovery
      - test_xml_collection_management
      - test_xml_poll
    protocol_bindings:
      - urn:taxii.mitre.org:protocol:http:1.0

  - id: test_xml_collection_management
    type: collection_management
    address: /services/test_xml_collection_management
    description: Custom Collection Management Service description
    protocol_bindings:
      - urn:taxii.mitre.org:protocol:http:1.0

  - id: test_xml_poll
    type: poll
    address: /services/test_xml_poll
    description: testing poll
    subscription_required: no
    max_result_count: 100
    max_result_size: 10
    authentication_required: no
    protocol_bindings:
      - urn:taxii.mitre.org:protocol:http:1.0


collections:
  - name: test-all-collection
    available: true
    accept_all_content: true
    type: DATA_SET
    service_ids:
      - test_all_inbox
      - test_all_collection_management
      - test_all_poll

  - name: test-xml-collection
    available: true
    accept_all_content: no
    type: DATA_SET
    service_ids:
      - test_xml_inbox
      - test_xml_collection_management
      - test_xml_poll

accounts:
  - username: username
    password: password
    is_admin: yes
`

And here is an image of my splunk threat intelligence 

![2018-06-13 2 44 03](https://user-images.githubusercontent.com/17289377/41310296-b313f280-6eb3-11e8-98ec-4e868085f8e3.png)

**Comment by traut** [comment]
@zacharycheng I might be mistaken, but that screenshot looks like a configuration for a simple HTTP downloader. There are no TAXII-specific configuration parameters. And OpenTAXII definitely does not take `collection=` POST argument. I think you're using wrong integration type or something here

**Comment by arcsector** [comment]
In the Type Field, note that it has to be `taxii`. Try that.

**Comment by arcsector** [comment]
@traut in splunk it's necessary to put the collection, username, and password as POST arguments, but Splunk passes them differently only if you specify Type as `taxii`. See my suggestion above

**Comment by arcsector** [comment]
Also see this: http://docs.splunk.com/Documentation/ES/5.1.0/Admin/Downloadthreatfeed#Add_a_TAXII_feed

**Comment by zacharycheng** [comment]
It works! Thanks guys!!! @arcsector I thought typing taxii in Type is an optional choice. Anyway, thanks!

**Comment by DerekKing** [comment]
This is quite old now - but i would love to see what config you ended up with. I have the same issue. Looks to me like you ended up turning off authentication. I have tried that too but still see unauthorised messages.

**Comment by DerekKing** [comment]
Also - is there a way I can see the request that actually gets sent from Splunk ? (debug option maybe)?

**Comment by arcsector** [comment]
@DerekKing please post splunk config page as well as opentaxii config files

**Comment by DerekKing** [comment]
Hi - I found my issue thank you. A little wireshark showed that Splunk sends basic auth with None:None in the header, which confuses the _authentication. I'll so a little write up and link over to here on how Splunk is implementing that. 

Thanks for the quick response!

**Comment by arcsector** [comment]
@DerekKing Thanks Derek. In the future please make a new issue and reference the closed one so we can have a record of issues to search through.
