### ISSUE TITLE
Polling Error

### ISSUE THREAD

**Issue by Mukesh0424** [eclecticiq/OpenTAXII#109]
Polling data from Taxii Server (OpenTaxii) using cabby is unsuccessful. I did validate the STIX files and they were pushed to the inbox successfully. Even then I get these two errors while polling :
1. 
![image](https://user-images.githubusercontent.com/10286141/41372761-dcc61546-6f6b-11e8-9f80-637b6e189537.png)

2.
![image](https://user-images.githubusercontent.com/10286141/41372795-f05c4378-6f6b-11e8-91d9-7c41ea9c2794.png)

Need help solving this issue

**Comment by traut** [comment]
@Mukesh0424 also, please make sure your webserver is not cutting long TAXII response short because of size limitations.

**Comment by Mukesh0424** [comment]
@arcsector,  @traut  ... It is working fine now.. Thank you so much for your inputs.
