### ISSUE TITLE
Database migrations

### ISSUE THREAD

**Issue by liger1978** [eclecticiq/OpenTAXII#110]
When upgrading a server with a PostgreSQL backend from OpenTAXII 0.1.9 to to OpenTAXII 0.1.10, what schema changes are required to the database before OpenTAXII processes are started using the new version?

**Comment by traut** [comment]
unfortunately, we didn't prepare this. you would have to compare model definitions to see the difference. or run 2 versions of opentaxii against fresh database, dump created schema and diff them

**Comment by liger1978** [comment]
In case anyone googles this.  Using a default install of OpenTAXII with SQLite, I couldn't find any difference in the persistence DB schema between 0.19 and 0.1.10.  There was a small difference in the auth DB schema. The SQL to migrate the SQLite auth DB from 0.1.9 to 0.1.10 is as follows:

```sql
ALTER TABLE accounts ADD COLUMN is_admin;
ALTER TABLE accounts ADD COLUMN _permissions;
```

**Comment by arcsector** [comment]
Thanks @liger1978 .
