### ISSUE TITLE
opentaxii-create-services  where is is

### ISSUE THREAD

**Issue by sbade1** [eclecticiq/OpenTAXII#112]
I was previously working with opentaxii and had it setup to use opentaxii-create-services, opentaxii-create-collections etc.  I had to stop this, and now I'm back, and when I install 0.1.10 via pip, those commands are not in the package.  Did i miss something in my install

**Comment by arcsector** [comment]
Hey there; now you use `opentaxii-sync-data`; check out the config file example in the repo for the format.

**Comment by sbade1** [comment]
aha  thanks

**Comment by sbade1** [comment]
Does this also replace the opentaxii-create-user command

**Comment by traut** [comment]
@sbade1 yep! check out the documentation -- http://www.opentaxii.org/en/stable/configuration.html#services-collections-and-accounts

**Comment by sbade1** [comment]
Thanks  Got past that problem.    Having an issue with fetching the collections.


I'm able to (with cabby)

a) discover the services (taxii-discovery --host otaxii.home --port 9000 --path /services/discovery --username access --password XXXXX --verify no --https)

b) Pull content (taxii-poll --host otaxii.home --port 9000 --verify no --https --discovery /services/discovery --username access --password XXXX --collection collection )


However when I try and discover the collections that are available with

taxii-collections --path https://otaxii.home:9000/services/collection-management --verify no --username access --password XXXX

I get a 404 error.  So obviously I have something wrong in the config.


This is the config file that I have syncd using (opentaxii-sync-data)


---


services:

  - id: inbox

    type: inbox

    address: /services/inbox

    description: Custom Inbox Service Description A

    destination_collection_required: yes

    accept_all_content: yes

    authentication_required: yes

    protocol_bindings:

      - urn:taxii.mitre.org:protocol:https:1.0



  - id: discovery

    type: discovery

    address: /services/discovery

    description: Custom Discovery Service description

    advertised_services:

      - inbox

      - discovery

      - collection

      - poll

      - collection_management

    protocol_bindings:

      - urn:taxii.mitre.org:protocol:https:1.0


  - id: collection_management

    type: collection_management

    address: /services/collection_management

    description: Custom Collection Management Service description

    protocol_bindings:

      - urn:taxii.mitre.org:protocol:https:1.0


  - id: poll

    type: poll

    address: /services/poll

    description: Custom Poll Service description

    subscription_required: no

    max_result_count: 100

    max_result_size: 10

    authentication_required: yes

    protocol_bindings:

      - urn:taxii.mitre.org:protocol:https:1.0



collections:

  - name: collection

    available: true

    accept_all_content: true

    type: DATA_SET


    service_ids:

      - inbox

      - collection_management

      - poll

      - discovery

(note, i removed the accounts section)


Any suggestions





--
Steven Bade  Director of Innovation and Integration
steve.bade@bluvector.io
518-469-1449


________________________________

**Comment by sbade1** [comment]
I cleared out my database and re-sync'd the configuration and now I'm able to do the discovery



--
Steven Bade  Director of Innovation and Integration
steve.bade@bluvector.io
518-469-1449


________________________________

**Comment by azimcap** [comment]
how?

**Comment by arcsector** [comment]
@azimcap the final comment is the solution; be more descriptive with your question.

**Comment by azimcap** [comment]
sorry @arcsector , I should had given more details.
I want to install TAXII server , I stuck here:

  ```
cp config/config.default.yaml config/config.yaml
Edit the db_connection parameters to match your environment. Change auth_api -> parameters -> secret whilst you're here as well.
```
I know I have to edit the config.yaml file. so how can you give example of the change I need in the following step:db_connection:
`db_connection: mysql://taxii/;some_password@localhost/taxiipersist`

I have edited to something like this :

 `mysql://root:secret@localhost/taxiipersist`

Is that correct?

thanks
