### ISSUE TITLE
Creating/modifying users

### ISSUE THREAD

**Issue by sbade1** [eclecticiq/OpenTAXII#114]
I've got my opentaxii service working well within our product within atomic.   I'm creating 2 default users (one admin and one with just read access), with opentaxii-sync-data using an input file based on the examples.  

What I'm looking for is a way to modify (e.g. change the password), or add/delete additional users without having to essentially re-create the whole input file and re-running sync-data.   I'm using postgress running in a different docker container (not using compose), and I thought I'd go and try to see what the schema looks like for auth, however (and i'm utterly clueless with respects to postgress), when I do a /dt when using the authdb, i get "no relationships found", so clearly I don't understand the persistence api.

There used to be a command /usr/bin/opentaxii-create-account command, but that appears to be gone.  

Any suggestions/pointers
(i'd prefer to not have to re-start the http server, but if that is necessary I can do that)

**Comment by traut** [comment]
@sbade1 there is no out-of-the-box management interface in OpenTAXII that would allow you to do that. You would need to change user account directly in the database. I'm not sure why you can't see the tables in your database. You can find model definitions for Auth and Persistence APIs implementation in `models.py` files in the repo

**Comment by sbade1** [comment]
thanks  i'll take a look..

**Comment by sbade1** [comment]
clearly my lack of postgres knowledge strikes.    once i found a cheat sheet (I was using "use auth", which is not the correct command to connect to the db which is "\c auth")  and now I can dump the table
