### ISSUE TITLE
Destination Collection Error returns Acceptable Destinations in extended_headers rather than status_detail

### ISSUE THREAD

**Issue by danielsamuels** [eclecticiq/OpenTAXII#115]
Version 1.1 of the TAXII Services Specification states that additional information relating to Status Messages should be provided in the Status Detail field, but in the OpenTAXII response to an Inbox Message containing no collection names when one or more is required, the Acceptable Destination values are returned in the `extended_headers` attribute instead.

You can see the block of code [here](https://github.com/eclecticiq/OpenTAXII/blob/7772520b5581f480d9e14d3ef10780e2ce22e1ee/opentaxii/taxii/services/inbox.py#L75-L79) which is causing the problem.  It looks like [StatusMessageException](https://github.com/eclecticiq/OpenTAXII/blob/7772520b5581f480d9e14d3ef10780e2ce22e1ee/opentaxii/taxii/exceptions.py#L19) will happily take a `status_details` attribute, so it seems like it just needs to be switched over.

**Comment by traut** [comment]
awesome point, @danielsamuels. made a pull request

**Comment by traut** [comment]
@danielsamuels merged. I'm closing this ticket
