### ISSUE TITLE
Difference between `max_result_size` and `max_result_count`

### ISSUE THREAD

**Issue by arcsector** [eclecticiq/OpenTAXII#122]
What is the difference between max `max_result_size` and `max_result_count`? What unit is `max_result_size` in? Bytes? Kilobytes?

**Comment by traut** [comment]
`max_result_size` — maximum TAXII response page size. If it is set to 50 (content blocks), OpenTAXII will split the response in pages by 50 content blocks;
`max_result_count` — maximum value for blocks count. If set to 100 but there are 1M content blocks in the collection, 100 will be returned. This setting can be used to hide real number of entities in a collection / set
