### ISSUE TITLE
taxii-discovery returns wrong service path

### ISSUE THREAD

**Issue by tokoivun** [eclecticiq/OpenTAXII#133]
So, finally got opentaxii running properly under gunicorn, bound to an external ip.

taxii-discovery can connect to the server, and it does give back the available services but for some reason the service path contains localhost instead of the ip address that the server is bound to. Any suggestions as to what is wrong.

taxii-discovery:

> pala@shizzle-DB:/opt# taxii-discovery --host nn.nn.nn.nn --port 9000 --path /services/discovery
> 2019-03-21 21:45:30,624 INFO: Sending Discovery_Request to http://nn.nn.nn.nn:9000/services/discovery
> 2019-03-21 21:45:30,640 INFO: 4 services discovered
> === Service Instance ===
>   Service Type: INBOX
>   Service Version: urn:taxii.mitre.org:services:1.1
>   Protocol Binding: urn:taxii.mitre.org:protocol:http:1.0
>   Service Address: http://localhost:9000/services/inbox
>   Message Binding: urn:taxii.mitre.org:message:xml:1.0
>   Message Binding: urn:taxii.mitre.org:message:xml:1.1
>   Inbox Service AC: []
>   Available: True
>   Message: Custom Inbox

And trying to push stix:

> pala@shizzle-DB:/opt# taxii-push --host nn.nn.nn.nn --port 9000 --discovery /services/discovery --content-file stix.xml --binding "urn:stix.mitre.org:xml:1.1.1"
> 2019-03-21 21:29:43,409 INFO: Sending Discovery_Request to http://nn.nn.nn.nn:9000/services/discovery
> 2019-03-21 21:29:43,424 INFO: 4 services discovered
> 2019-03-21 21:29:43,425 INFO: Sending Inbox_Message to http://localhost:9000/services/inbox
> 2019-03-21 21:29:43,514 ERROR: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters

**Comment by arcsector** [comment]
Please post your opentaxii server config yml; the one that looks like the example [here](https://github.com/eclecticiq/OpenTAXII/blob/master/opentaxii/defaults.yml).

**Comment by tokoivun** [comment]
---
domain: "nn.nn.nn.nn:9000"
support_basic_auth: yes
save_raw_inbox_messages: no
xml_parser_supports:huge_tree: yes

persistence_api:
  class: opentaxii.persistence.sqldb.SQLDatabaseAPI
  parameters:
    db_connection: mysql://taxii:<password>@<db address>:3306/taxiipersist
    create_tables: yes

auth_api:
  class: opentaxii.auth.sqldb.SQLDatabaseAPI
  parameters:
    db_connection: mysql://taxii:<password>@<db address>:3306/taxiiauth
    create_tables: yes
    secret: <secret>

logging:
  opentaxii: info
  root: info

zmq:
    host: <zmg address>
    port: 50000

misp:
    url: "https://<misp address>"
    api: <apikey>
    verifySSL: False

taxii:
    auth:
        username: taxii
        password: <password>
    collections:
        - collection

**Comment by tokoivun** [comment]
Well, no idea how to get redactions work cleanly :( But the domain field contains the external IP address.

OpenTAXII is also running under gunicorn, with binding on the same IP and port.

**Comment by arcsector** [comment]
What's your command to start the service in gunicorn? Because if you're using `opentaxii-start-dev` it will always return localhost

**Comment by tokoivun** [comment]
nohup gunicorn opentaxii.http:app --bind nn.nn.nn.nn:9000 --config python:opentaxii.http &

**Comment by arcsector** [comment]
Have you exported your `OPENTAXII_CONFIG` variable? It  may be that opentaxii is still using default config...

**Comment by tokoivun** [comment]
I had it exported. I'll doublecheck

**Comment by arcsector** [comment]
imo best way to check is make sure that `/tmp/*.db` doesnt exist.

**Comment by tokoivun** [comment]
well, FML... Apparently it was not exported. Or does ". venv/bin/activate" reset environmental variables? In either case, works now. Thanks!

**Comment by arcsector** [comment]
No problem. Please close the issue.
