### ISSUE TITLE
Method not Allowed (gunicorn)

### ISSUE THREAD

**Issue by DerekKing** [eclecticiq/OpenTAXII#136]
Hi 

I have a working config in such much as I can use cabby to post docs, and query them using Splunk (over http for now), but what I can't do is use my browser to navigate to any of the endpoints (poll, discovery etc), since the browser uses a GET request, and it seems opentaxii expects POST. 

What am i missing here, should it be possible to use the browser to goto to http://xx.xx.xx.xx:9000/services/poll-a as an example ? If it is, could you suggest a config for me to wrap my head around please ?

**Comment by arcsector** [comment]
Since there's no Jinja templates, you actually will have to create a GUI yourself. I don't know what you would want to do with those endpoints, but good luck.

**Comment by DerekKing** [comment]
thanks @arcsector - It was really a question as to whether it should be possible. I guess I thought I could poll the collection and have the browser display STIX objects that could be copied/pasted.

Am I way off the mark ?

**Comment by arcsector** [comment]
Yes you are. although you could do it with some mild extension. The idea of TAXII is in the name; Automated. Browsers just aren't automated. Hence the lack of browser support.

**Comment by DerekKing** [comment]
Brilliant thanks. Really appreciate the response.
