### ISSUE TITLE
OpenTAXII running in a Docker is not accessible from the web browser

### ISSUE THREAD

**Issue by srtimsina** [eclecticiq/OpenTAXII#140]
OpenTAXII running in a Docker is not accessible from the web browser. Docker container was started with the following command.
 `docker run -d -p 9000:9000 eclecticiq/opentaxii`

Is there anything to do before we are able to browse the server?

**Comment by arcsector** [comment]
Its not meant to be accessible via web browser. Please close the issue.

**Comment by traut** [comment]
@srtimsina please post the messages you sent to the mail here

**Comment by srtimsina** [comment]
> Its not meant to be accessible via web browser. Please close the issue.
Hi, @arcsector it's not clear yet. Can you pls explain?

**Comment by srtimsina** [comment]
> @srtimsina please post the messages you sent to the mail here

Hi, @traut here you go,
We need to authenticate the user before they are able to fetch the data from OpenTAXII server. I believe that OpenTAXII supports password/ client key authentications.
We have deployed OpenTAXII on a docker on port 9000. Now we need to fetch data from the server with the authentication enabled, both(password and key based). But i could not find the proper instruction to get that.

**Comment by arcsector** [comment]
@srtimsina Thank you.
