### ISSUE TITLE
send STIX (json) file to ELK

### ISSUE THREAD

**Issue by mhbitman** [eclecticiq/OpenTAXII#143]
I want to integrate OPENTAXII and ELK, to sned json file to opentaxii and save them in elk. both of them are installed as docker container.
in default configuration ELK send bad syntax error because of nested json file.
How can I match these containers?

**Comment by traut** [comment]
do I understand correctly, that you want to use Elastic as a backend DB for OpenTAXII?

> in default configuration ELK send bad syntax error because of nested json file.
I'm not sure I understand. If you want to send data to OpenTAXII and store it in ELK, why ELK sends anything?

**Comment by arcsector** [comment]
@mhbitman Please post your ELK stack configs, DB backend you're using, and port configs.

**Comment by arcsector** [comment]
@mhbitman Any updates to this?

@traut Stale issue? Coming up on 5 months with no reply...

**Comment by traut** [comment]
@arcsector will close it in a couple of days if no updates from OP

**Comment by traut** [comment]
no updates, closing
