### ISSUE TITLE
Refactor exceptions

### ISSUE THREAD

**Issue by orsinium** [eclecticiq/OpenTAXII#150]
Let's do fewer exception types, drop intermediate exceptions etc. See https://github.com/eclecticiq/OpenTAXII/pull/149#discussion_r332065638 for context

**Comment by eric-eclecticiq** [comment]
We have recently made a decision to consider this project feature-complete. It means we still maintain it, however we focus only on bug fixes. As this issue is a feature request, unfortunately we won’t add it and therefore I’m closing this issue.

**Comment by orsinium** [comment]
It's not a feature nor a bug, it's refactoring. Elixir is also feature-complete but they still do internal clean-ups. "Feature-complete" means a stable interface, not reducing maintenance cost.

**Comment by eric-eclecticiq** [comment]
Every project has its own approach :) Unfortunately this project is closer to an end of life where refactoring is not our concern any more except for critical bugs. Feel free to fork the project if you really need those changes.
