### ISSUE TITLE
What is the purpose of subscription in OpenTAXII

### ISSUE THREAD

**Issue by yuriyvolkov** [eclecticiq/OpenTAXII#152]
Hi there,

First of all - thank you for the OpenTAXII implementation.

We've been exploring OpenTAXII use cases in regard to the TAXII architecture implementation of the Source/Subscriber model. Based one the dive into the source code we've concluded that 'content push' from the `Source` to `Subscriber` is not supported at the moment and existing subscription implementation can only be used for content binding filtering during polls (i.e. poll only `urn:stix.mitre.org:xml:1.1.1` for example). Did we get it right?

Thanks in advance.

**Comment by arcsector** [comment]
I think you're asking if there's any built-in implementation for source-subscriber model, and not just writing your own script to be called by flask?

**Comment by traut** [comment]
if I understand correctly, you can achieve your goal by using dedicated collections, that are attached to both Inbox and Poll services. This way source can push data into a collection, and subscriber can fetch the data

**Comment by yuriyvolkov** [comment]
@arcsector I see no support for `Delivery Parameters` defined in http://docs.oasis-open.org/cti/taxii/v1.1.1/cs01/part2-services/taxii-v1.1.1-cs01-part2-services.html#_Toc450734209  and http://docs.oasis-open.org/cti/taxii/v1.1.1/cs01/part2-services/taxii-v1.1.1-cs01-part2-services.html#_Toc450734209

> Delivery Parameters: This field identifies the parameters used to push content to the Consumer in fulfillment of a subscription. This field is only meaningful if the Action field is equal to SUBSCRIBE and is ignored for all other Action values.  The absence of this field for a SUBSCRIBE action indicates that the requester is not requesting pushed content and will instead poll for subscription content use a Poll Service. In this case, if the TAXII Data Collection cannot be polled, a Status Message with a status of 'Polling Not Supported' SHOULD be returned.

I assume there should be corresponding columns in the Subscription data model to store delivery params if this is supported.

@traut in the source/subscriber model, if I understand it correctly, it is the `Source` which pushes new content onto the `Subscriber` Inbox service using `Delivery Params` provided during the subscription.

**Comment by yuriyvolkov** [comment]
I'm referring here to the TAXII Architecture as outlined in http://docs.oasis-open.org/cti/taxii/v1.1.1/cs01/part1-overview/taxii-v1.1.1-cs01-
![](http://docs.oasis-open.org/cti/taxii/v1.1.1/cs01/part1-overview/taxii-v1.1.1-cs01-part1-overview_files/image006.png)

**Comment by traut** [comment]
@yuriyvolkov ah, I understand now. No, for simplicity OpenTAXII does not support active subscription module, where content is pushed to subscribers.

**Comment by yuriyvolkov** [comment]
@traut what is the use case of subscription in OpenTAXII then? The only use case I can think of is to subscribe only for the specific content_bindings if a collection supports more that one (like `urn:stix.mitre.org:xml:1.1.1` and `urn:custom.bindings.com:json:0.0.1`).

**Comment by traut** [comment]
@yuriyvolkov yeah, in OpenTAXII it's pretty much the only thing Poll parameters record [will store](https://github.com/eclecticiq/OpenTAXII/blob/master/opentaxii/taxii/services/handlers/subscription_request_handlers.py#L54). I think Subscription model is one of the weakest parts of TAXII spec, and that's why it is not used much in the wild

**Comment by yuriyvolkov** [comment]
@traut is it possible to disable subscription requests at all so that collection management requests won't list subscription as an option alongside poll?

**Comment by traut** [comment]
@yuriyvolkov collections will have "subscription service" block in their description, if they are connected to [any CollectionManagement service](https://github.com/eclecticiq/OpenTAXII/blob/971605a5a27c38cfe324bfc8588d2fc708a5d11e/opentaxii/taxii/services/collection_management.py#L61) with `subscription_supported` set to `True`. This is something you can [configure per CollectionManagementService](https://github.com/eclecticiq/OpenTAXII/blob/7772520b5581f480d9e14d3ef10780e2ce22e1ee/opentaxii/taxii/services/collection_management.py#L35).

**Comment by yuriyvolkov** [comment]
@traut what about "receiving inbox service" - is it possible to not advertise it in the collection description if user has only "read" permission?

**Comment by traut** [comment]
@yuriyvolkov of course! If collection is not attached to an inbox service, it will not advertise it

**Comment by yuriyvolkov** [comment]
@traut if a collection is not attached to an inbox service, then how do I push content into that collection?

**Comment by traut** [comment]
ah, sorry, misread. In this case, you would have to [enforce authentication](https://github.com/eclecticiq/OpenTAXII/blob/master/examples/data-configuration.yml#L20) in Inbox / Poll services and use proper [permissions per account](https://github.com/eclecticiq/OpenTAXII/blob/master/examples/data-configuration.yml#L101) for access control.

**Comment by yuriyvolkov** [comment]
but `Inbox` service would still be listed alongside `Polling` service in the collection description even if an authenticated user has only read permission. Might checking for the `can_modify` permission in https://github.com/eclecticiq/OpenTAXII/blob/master/opentaxii/taxii/services/collection_management.py#L83 be a good idea?

**Comment by traut** [comment]
indeed, it might be a good idea. Does current behaviour cause you any issues right now?

**Comment by yuriyvolkov** [comment]
@traut not yet as we're about to launch a CTI service using OpenTAXII in the upcoming weeks. It just doesn't make any sense from the UX perspective to advertise the availability of Inbox service for read-only users.

**Comment by traut** [comment]
@yuriyvolkov one solution might be to implement access control filtering in custom Persistence API

**Comment by yuriyvolkov** [comment]
> but `Inbox` service would still be listed alongside `Polling` service in the collection description even if an authenticated user has only read permission. Might checking for the `can_modify` permission in https://github.com/eclecticiq/OpenTAXII/blob/master/opentaxii/taxii/services/collection_management.py#L83 be a good idea?

@traut mind accepting a PR for the above if I'll raise one?

**Comment by traut** [comment]
@yuriyvolkov sure, but for [PersistenceManager](https://github.com/eclecticiq/OpenTAXII/blob/master/opentaxii/persistence/manager.py) (that's where access is checked), not for CollectionManagement service.

**Comment by yuriyvolkov** [comment]
@traut So I'm going to put additional logic into  `get_services_for_collection` to filter out inbox services if a user has no `modify` permission - are you OK with that?

**Comment by traut** [comment]
sounds good, thank you
