### ISSUE TITLE
support for ENV vars based config

### ISSUE THREAD

**Issue by yuriyvolkov** [eclecticiq/OpenTAXII#154]
Is there any interest in the environment vars based OpenTAXII config implementation? So that instead of using YAML files to store DB creds, etc they would be passed via env vars (as outlined in https://12factor.net/config)? 

That would allow getting rid of https://github.com/eclecticiq/OpenTAXII/blob/master/docker/entrypoint.sh#L64-L95 and avoid credential dumping into docker logs (which is as bad as it sounds).

**Comment by arcsector** [comment]
Are you willing to make a PR for this?
