### ISSUE TITLE
Error with 2-byte characters cabby push

### ISSUE THREAD

**Issue by over320** [eclecticiq/OpenTAXII#155]
Hi
I have built an OpenTaxii server. The build was successful, and the STIX push / poll was also successful.
However, if Japanese characters (UTF-8 encoded 2-byte characters) exist in STIX Content, an error will occur at the time of push. The details of the error are as follows.
“All strings must be XML compatible : Unicode or ASCII, no NULL byte or control characters.”

Can you tell me a workaround for this error?

**Comment by arcsector** [comment]
@over320 i do believe that due to XML specification, you must use all ascii characters. Thus, the way to deal with this in STIX is to escape the character and print that instead.

Do you have the sample document you can link to or is it confidential?

**Comment by arcsector** [comment]
Hi @over320,

Can you link to the document? If not, you may need to escape the unicode character.

**Comment by over320** [comment]
Hi arcsector

Thanks for your comment. I have a question.
When do I escape the Unicode characters?  Do I add escape before push STIX, and remove the escape after pull?

**Comment by orsinium** [comment]
What is Python version you use for OpenTAXII? It can occur on Python 2:

https://stackoverflow.com/questions/17138088/french-and-lxml-text

If so, can you run OpenTAXII on Python 3.5+?

**Comment by arcsector** [comment]
@over320 escape it on ingest; most threat Intel searches are on stringified data, so if that character is escaped, it should match on the stringified data. 

In other cases, it will ignore the character.

**Comment by traut** [comment]
@over320 were you able to solve the issue?

**Comment by over320** [comment]
Everyone
Thank you for your advice. By escaping double-byte characters, I can successed push / poll.
