### ISSUE TITLE
Build wheel

### ISSUE THREAD

**Issue by orsinium** [eclecticiq/OpenTAXII#156]
Please, upload whl packages for opentaxii on pypi. Wheels faster, more clear and secure. Sdists require setup.py execution step that can be quite painful.

**Comment by eric-eclecticiq** [comment]
We have recently made a decision to consider this project feature-complete. It means we still maintain it, however we focus only on bug fixes. As this issue is a feature request, unfortunately we won’t add it and therefore I’m closing this issue.

**Comment by orsinium** [comment]
Welcome to the team, Eric :) This is not a feature request, I think. We had a few issues because of setup.py execution (#157). Also, all the dependencies are installed on CI on every pipeline run, and installation of wheels is much faster. Build it once, reduce GitLab CI runners costs forever. I'd consider doing it, it's actually easy:

```bash
python3 -m pip install wheel
python3 setup.py bdist_wheel
twine upload dist/*.whl
```

The reason I haven't done it is that I didn't have access to the pypi package.

**Comment by eric-eclecticiq** [comment]
Thank you for your clear explanation, they might still help in the future. Our current position to stop refactoring as well is that it could create new bugs, as any new code, we would have to fix afterwards. And it is not something we want now. Feel free to fork the project if you really need those changes.
