### ISSUE TITLE
http://127.0.0.1:9000/ Not Found

### ISSUE THREAD

**Issue by skyforblue** [eclecticiq/OpenTAXII#159]
I run `opentaxii-run-dev` in line but show me error that Not Found

**Comment by arcsector** [comment]
Can you provide a little more info? OS, python version, `pip freeze` and other basic troubleshooting steps??

**Comment by Applenice** [comment]
If you are using a web browser, you should see this error:
```
Not Found
The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```
The answer can be found here：
https://github.com/eclecticiq/OpenTAXII/issues/140#issuecomment-530724642
>It's only meant to be accessible via REST API; do you see any HTML/JS files in the repo? There is no support for web browser, only CLI. Follow the instructions listed in the documentation to poll using cabby here.
