### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by Sunlgl** [eclecticiq/OpenTAXII#160]
Hello! Can you tell me how to use it, or what APIs are available for it

**Comment by traut** [comment]
please take a look at [the documentation](http://opentaxii.org/).

**Comment by Sunlgl** [comment]
I have read the document. At present, I don't know how to use it, for example, what specific data or some specific functions it can produce. Thank you very much

**Comment by traut** [comment]
@Sunlgl if the documentation was not enough and you would like us to help you, please provide a specific question

**Comment by Sunlgl** [comment]
OK, what specific APIs can I call together? Do I need the curl command to call them

**Comment by traut** [comment]
@Sunlgl please refere to TAXII 1.1 spec for that -- https://taxiiproject.github.io/releases/1.1/

**Comment by Sunlgl** [comment]
OK，thanks! Besides，How can I interact with opentaxii? For example, I have a threat intelligence event

**Comment by traut** [comment]
@Sunlgl please read the spec to understand what TAXII can provide for you. You can interact with OpenTAXII via ways defined in the spec

**Comment by arcsector** [comment]
Hi @Sunlgl,

Please provide exactly what step you are at in the documentation, what you are trying to accomplish, what steps you have tried, what your environment is (python version, os, etc...), and other relevant information. 

If you cannot provide this information, then i do not know how to help you.

**Comment by Sunlgl** [comment]
I've configured and run OpenTAXII according to the documentation, got a 404 error in the browser like everyone else, and now I want to know what kind of data it can output, like I have some threat intelligence, how do I get that threat intelligence to interact with OpenTAXII
python2.7 and 3.4, mac system
