### ISSUE TITLE
Configuration documentation

### ISSUE THREAD

**Issue by joseph-gagnon** [eclecticiq/OpenTAXII#163]
Although there are a number of documentation pages on the OpenTAXII web site (i.e. http://www.opentaxii.org/en/stable/configuration.html), there does not appear to be anything that provides a comprehensive detailed reference for the configuration parameters that can be used.

Does this information exist somewhere?

**Comment by traut** [comment]
@joseph-gagnon unfortunately there is no extensive configuration documentation now. You can find all supported options in the [default config file](https://github.com/eclecticiq/OpenTAXII/blob/master/opentaxii/defaults.yml).
