### ISSUE TITLE
OpenTAXII - TAXII v2.x protocol implementation

### ISSUE THREAD

**Issue by gmellini** [eclecticiq/OpenTAXII#167]
Hi all,
I'm trying to understand how implement STIX2 over TAXII2.x in OpenTAXII.

I found the way to push STIX2 over TAXII1.x #165 and I understood that TAXII1.x is protocol agnostic so you can push/poll STIX2 content without problems using ```taxii-push``` and ```taxii-poll```

I tried to connect to the inbox with an external STIX2 client (a minemeld miner in my case) but the client try using TAXII2; this means taht I receive an error because TAXII2.x endpoints where not implemented in OpenTAXII
http://docs.oasis-open.org/cti/taxii/v2.0/cs01/taxii-v2.0-cs01.html#_Toc496542712
https://docs.oasis-open.org/cti/taxii/v2.1/cs01/taxii-v2.1-cs01.html#_Toc31107514

The question is: is TAXII2.x implemented in OpenTAXII and if so how I can enable TAXII2 enpoints?

Tks for your time
merlos

**Comment by traut** [comment]
OpenTAXII does not implement TAXII2 protocol just yet, only TAXII 1.0/1.1. 

TAXII2 support is on the roadmap but I have no ETA for it yet

**Comment by gmellini** [comment]
Is there anyone working on it or a dev branch where I (and others) can contribute?

**Comment by arcsector** [comment]
@gmellini Can you submit a PR and maybe @traut can merge it into a development branch?

**Comment by gmellini** [comment]
of course, will do. tks

**Comment by eric-eclecticiq** [comment]
Hi, thanks for opening an issues!

We have recently made a decision to consider this project feature-complete. It means we still maintain it, however we focus only on bug fixes. As this issue is a feature request, unfortunately we won’t add it and therefore I’m closing this issue.

**Comment by testmode0450** [comment]
@eric-eclecticiq I am not able configure the taxii 2.x in opentaxii, because when I disbale taxii 1.x and configuring taxii 2.x I am getting error is their any bug or  I am missing soming
this is my default.yml file
---

domain: "localhost:9001"

support_basic_auth: yes
return_server_error_details: no

auth_api:
  class: opentaxii.auth.sqldb.SQLDatabaseAPI
  parameters:
    db_connection: postgresql://postgres:password@localhost:5432/mydb
    create_tables: yes
    secret: aueHenjitweridUcviapEbsJocdiDrelHonsyorl
    token_ttl_secs: 3600

taxii2:
        persistence_api:
                class: opentaxii.persistence.sqldb.SQLDatabaseAPI
                parameters:
                        db_connection: postgresql://postgres:password@localhost:5432/mydb
                        create_tables: yes
logging:
  opentaxii: info
  root: info

**Comment by testmode0450** [comment]
@eric-eclecticiq It is working well when i configure Taxii 1.x in opentaxii

**Comment by JohanPhom** [comment]
Is Taxii v2 now supported ? Or still in development ?
