### ISSUE TITLE
opentaxii server worker timeout

### ISSUE THREAD

**Issue by zacharycheng** [eclecticiq/OpenTAXII#168]
Hi, I am using Opentaxii server for like a year . 
However, recently I found that the taxii server is not able to be poll any result from the TAXII server. 

On the client side shows an error message of 

> ERROR: ('Connection aborted.', BadStatusLine("''",))

On the server side, I am running gunicorn with a config file with the following setting 

> worker_connections: 6000
 workers: 2
backlog: 2048
bind: ['0.0.0.0:9000']
worker_class: gevent

Below is my opentaxii config

>domain: "ip:9000"
support_basic_auth: yes
save_raw_inbox_messages: yes
xml_parser_supports_huge_tree: yes
count_blocks_in_poll_responses: no
return_server_error_details: yes
persistence_api:
  class: opentaxii.persistence.sqldb.SQLDatabaseAPI
  parameters:
    db_connection: postgresql://user:pw@localhost:5432/PersisAPI
    create_tables: yes
auth_api:
  class: opentaxii.auth.sqldb.SQLDatabaseAPI
  parameters:
    db_connection: postgresql://user:pw@localhost:5432/AuthAPI
    create_tables: yes
    secret: thereisnosecrethere
logging:
  opentaxii: debug
  root: debug

I have no idea which part goes wrong?
Is there any ways to troubleshoot which part goes wrong?

Would it be possible due to the large size of data stored in database? 
There are over 270000 records in the table.

**Comment by arcsector** [comment]
Hi Zachary,

First off, please use the code block formatting next time for your config files, although the code block works as a secondary option. 

It's not the number of entries in the database; my DB is over 750GB, so it's definitely not that.

Can you configure gunicorn to capture stdout and stderr and log those so that we can see what opentaxii spits out? The config to do this is: [capture_output](https://docs.gunicorn.org/en/stable/settings.html#capture-output).

**Comment by traut** [comment]
@zacharycheng do you run any webserver in front of the gunicorn server?

**Comment by Sphynx-HenryAY** [comment]
I encounter a similar problem, the worker will be killed around 80% ram usage, and client would throw connection timeout error.
my machine is with 2 cores and 4GB ram, would @arcsector share your spec for me as reference?
this problem occurs only when the sub-collection selected is big, around 55000 content blocks, would it be a problem?

**Comment by traut** [comment]
@Sphynx-HenryAY does it happen only when you send `poll` query?

**Comment by Sphynx-HenryAY** [comment]
@traut yes, it does happens only when polling

**Comment by arcsector** [comment]
@Sphynx-HenryAY Are you polling the entire collection?

**Comment by eric-eclecticiq** [comment]
The issue is closed because of inactivity. The issue could be open again if additional information is provided to justify it is a OpenTAXII bug. A reproducible way to create the bug is of course welcome.
