### ISSUE TITLE
Push JSON STIX to opentaxii server

### ISSUE THREAD

**Issue by dtp36** [eclecticiq/OpenTAXII#171]
Can anyone point me to an example of how to push a JSON STIX object to an opentaxii server, for example by using the cabby client or by another method?

**Comment by arcsector** [comment]
Cabby's default [examples](https://cabby.readthedocs.io/en/stable/user.html#using-cabby-as-a-command-line-tool) should work just fine. OpenTAXII is content agnostic, so you should be fine. Please post what you have tried so far and what the errors were.

**Comment by lcia-projects** [comment]
@arcsector that examples link no longer works, i've looked at the cabby github and see no examples. Do you have any other suggestions?

**Comment by arcsector** [comment]
@lcia-projects try this link: https://cabby.readthedocs.io/en/latest/user.html#using-cabby-as-a-command-line-tool
