### ISSUE TITLE
Compatibility and system requirements?

### ISSUE THREAD

**Issue by ohliuw** [eclecticiq/OpenTAXII#175]
Can't find any info on compatibility and system requirements? Can it run on RH? Also,. what is the recommended system requirements?

Thanks

**Comment by arcsector** [comment]
If by RH you mean Red Hat, yes you can run it on Red Hat. Minimum requirements aren't a thing, but I've had success running a minimal setup with 4vCPU and 8GB memory, when only running the sqlite DB. However at scale I'd recommend a separate DB machine and 8vCPU with 16-32GB memory.

**Comment by eric-eclecticiq** [comment]
> Can it run on RH?

Yes Red Hat and Cent Os.

> compatibility and system requirements?

The TAXII server needs a DB that should run either locally on the server or in another server accessible through the network. 

> what is the recommended system requirements?

It will really depend on your use case (load, availability...). I recommend to adapt your setup after doing some real use case tests.
