### ISSUE TITLE
No Database Schema Diagram

### ISSUE THREAD

**Issue by arcsector** [eclecticiq/OpenTAXII#177]
I feel like there should be a good schema diagram that exists to show the relationship between each of the tables created for OpenTAXII. Does this exist and it hasn't been included for a good reason, or does it not exist and it needs to be created and added to the docs?

**Comment by eric-eclecticiq** [comment]
Hi, thanks for opening an issue!

> It does not exist and it needs to be created and added to the docs

However it’s not a high priority for our team at the moment, so we can’t promise when it will get fixed. Still, we’re very open to external contributions - if you know how to fix this and you can open a PR with a change, we will be very grateful.
