### ISSUE TITLE
How to use Persistence API to query pushed messages?

### ISSUE THREAD

**Issue by wizardous23** [eclecticiq/OpenTAXII#178]
Hello, I've been able to push a STIX object message to my collection. I just wanted to ask where the messages are stored after a push (taxii-push command) and how can they be queried?

**Comment by arcsector** [comment]
Hi Wizardous,
The best way to see how to do this is to read the documentation. Other than that, you can use the cabby command taxii-pull to query the object. You can also directly query the SQL backend by grabbing the `content_blocks` table.

**Comment by wizardous23** [comment]
> Hi Wizardous,
> The best way to see how to do this is to read the documentation. Other than that, you can use the cabby command taxii-pull to query the object. You can also directly query the SQL backend by grabbing the `content_blocks` table.

The content_blocks table seems to be in JSON if I am not wrong? Are there any helper functions that would help query this data based on the created_at tag?

**Comment by arcsector** [comment]
Again, please read the documentation for cabby; look for the `begin` and `end` arguments
