### ISSUE TITLE
Make URL harvesting impossible

### ISSUE THREAD

**Issue by traut** [eclecticiq/OpenTAXII#18]
At the moment it is possible to discover URLs of the protected services.

When client sends a request without a token (or with invalid token), OpenTAXII doesn't know if authentication is required for the service, so first it has to configure service instance. If a service does not exist, `404 NOT FOUND` will be returned. if service is configured and requires authentication, `UNAUTHORIZED` will be returned. 

So it is possible to walk all possible URLs and log the ones with `UNAUTHORIZED`. This is a configuration leak.

**Comment by traut** [comment]
Conceptually, maybe the server instance needs to have auth required/not required switch as well (configured services already have that)

**Comment by arcsector** [comment]
I can do this for you, but would I replace all the `raise UnauthroizedException()` in `opentaxii/middleware.py` with `abort(404)` to solve this? Or would you just `raise UnauthorizedException()` where you would normally `abort(404)`?

Seems like I might also just be able to replace both of them with a general error such as `Error: Failure` which is defined in `opentaxii/taxii/exceptions.py`.

Are any of these viable solutions?
