### ISSUE TITLE
default Docker image is not working.

### ISSUE THREAD

**Issue by azurekid** [eclecticiq/OpenTAXII#217]
When trying to spin-up the default provided container, this one seems not to start.

**Comment by erwin-eiq** [comment]
@azurekid thank you for the bugreport. I'm looking into it.

**Comment by azurekid** [comment]
Please let me know if I can provide you more information 🙏🏼

**Comment by erwin-eiq** [comment]
It was actually quite easy to reproduce and fix. Thanks again for reporting. 

I've just pushed `0.3.0a3` with the fix and I'm awaiting the dockerhub build now to verify that all is well.

**Comment by erwin-eiq** [comment]
Fix confirmed. @azurekid you'll probably have to run `docker pull eclecticiq/opentaxii` to get docker to pull the latest image.

**Comment by azurekid** [comment]
You are a Rockstar!
