### ISSUE TITLE
Question: Docker Container Download Delays with Kitematic?

### ISSUE THREAD

**Issue by packet-rat** [EclecticIQ/OpenTAXII#39]
I'm attempting to load the Docker OpenTAXII Image using Kitematic (https://kitematic.com) under Mac OSX after an hour and a half it's sitting at ~96%. Anyone else seeing this and have any suggestions?

**Comment by packet-rat** [comment]
Confirmed issues with manual pulls (e.g. bash-3.2$ docker run -d -p 9000:9000 intelworks/opentaxii).  Certain images hosted on cloudfront.net took an exhorbitent amount of time to download. 


Status: Downloaded newer image for intelworks/opentaxii:latest docker.io/intelworks/opentaxii: this image was pulled from a legacy registry.  Important: This registry version will not be supported in future versions of docker.
07704f43e903d57e6af9d94a623a8b4e2cae0f0b661b450bdb2f212d30b24b4c
bash-3.2$

**Comment by code040** [comment]
did you restart the 'pull' at any time? or start a new one while the other was still going? It is common when that happens, that docker can get in a deadlock state. Only solution is then to restart the docker process and do a 'pull' again.

**Comment by code040** [comment]
@packet-rat Are you still having issues with this? Please also note that we have moved to a new name for the docker images: eclecticiq/opentaxii
