### ISSUE TITLE
How to Age-Out (Purge Old) Data?

### ISSUE THREAD

**Issue by nickwallen** [EclecticIQ/OpenTAXII#45]
Is there a mechanism to purge or age-out old data with OpenTAXII?  How do I ensure that the data store doesn't grow without bounds?

**Comment by traut** [comment]
@nickwallen default SQL backend does not support any clean-up procedures at the moment. 

What would be your requirements here?

**Comment by nickwallen** [comment]
I am looking at integrating OpenTAXII as a source of threat intel data for the default deployment of Apache Metron.  In most cases, I envision Metron users leveraging their own existing aggregator platform that would be used instead.  Although if none exists, I am hoping that OpenTAXII can fill that role.

I have [some logic that I will likely be added to Metron](https://github.com/apache/incubator-metron/pull/85) that deploys OpenTAXII and can sync with some external 3rd party feeds.  If I setup a mechanism that continually syncs external threat intel feeds, I need to ensure that the data store size doesn't grow without bound.  That's what I need.

**Comment by code040** [comment]
Are you planning of running this using the SQLite database?  Then all you can do is implement a cleanup routine inside the persistence layer (and possible in the manager), which runs periodically any cleanup task.  As @traut mentioned, this is currently not the case.

**Comment by traut** [comment]
@nickwallen another option would be to implement another OpenTAXII CLI command to clean-up DB. Something as simple as "delete content blocks older than X in collections A and B". Host admin can use this inside scheduled cron jobs // @code040

**Comment by nickwallen** [comment]
Yes, I like that idea.  Ideally, it would work the same no matter what persistence API (sqlite, mysql, etc) is used.
