### ISSUE TITLE
User authorization per collection

### ISSUE THREAD

**Issue by chorsley** [eclecticiq/OpenTAXII#50]
Are there currently plans or recommended approaches for authorizing user access to particular collections? Moreover, is there a way to have some collections as read-only and some as read-write per-user?

Additionally, this would mean that users are only shown the collections they have access to when they access the discovery service.

This is something along the lines of what is discussed at https://github.com/TAXIIProject/django-taxii-services/issues/35.

**Comment by traut** [comment]
Recommended approach here would be to provide custom persistence API implementation. It can use `opentaxii.local.context.account` value (set during authentication) to filter collections/services returned to the client, ensuring that every client sees only collections/services available to him.

**Comment by chorsley** [comment]
I'd imagine we'd also need some kind of admin UI potentially, and user group support if we were doing it right. But for now, noted, thanks.

**Comment by traut** [comment]
@chorsley yes, we have some plans about admin UI and better authentication management. I'm not sure about the timeline for that though

**Comment by arcsector** [comment]
@traut This should be closed once the documentation is updated

**Comment by traut** [comment]
new [release 0.1.10](https://github.com/eclecticiq/OpenTAXII/releases/tag/0.1.10) is published.
