### ISSUE TITLE
Installation problems with MySQL

### ISSUE THREAD

**Issue by FloatingGhost** [EclecticIQ/OpenTAXII#51]
Hey there, I hope I'm not doing anything stupid in my installation process, but I can't seem to get the TAXII server running with MySQL

I'm using Python3.5 if that helps. *Should* be compatible I think. 

Process:
```bash
git clone [repo URL]
cd OpenTAXII
sudo python3 setup.py install
mysql -u [username] -p
  # Create dbs taxiipersist and taxiiauth
export OPENTAXII_CONFIG=[full path]
opentaxii-create-services -c services.yaml
```

I then get a big damn list of errors that I piped out, attached as errors.txt

All my config files are attached as well, just in case I somehow messed up there.

Thanks in advance :)

[config_files.zip](https://github.com/EclecticIQ/OpenTAXII/files/599708/config_files.zip)
[errors.txt](https://github.com/EclecticIQ/OpenTAXII/files/599727/errors.txt)

**Comment by aukjan** [comment]
Hey @FloatingGhost, thank you very much for letting us know. We will investigate.  This seems to be related to MySQL specific options.  (We use PostgreSQL internally).

**Comment by traut** [comment]
@FloatingGhost We were not specifying length of String column type and (apparently) it is required for MySQL backend. I just pushed fix for that to master. Please verify.

**Comment by FloatingGhost** [comment]
Well that's one error fixed, but up pops another :D

`(1170, "BLOB/TEXT column 'name' used in key specification without a key length") [SQL: 'CREATE UNIQUE INDEX ix_data_collections_name ON data_collections (name)']`

Full text attached
[new_error.txt](https://github.com/EclecticIQ/OpenTAXII/files/599790/new_error.txt)

**Comment by traut** [comment]
ahaha, let me see if length is required for `TEXT` as well

**Comment by traut** [comment]
ok, another try with 03526996a1a40a7b6df15b03e9c528cd69c5232e

Please try again. Sorry, I do not have MySQL env available to verify myself.

**Comment by FloatingGhost** [comment]
Success! Thanks <3

**Comment by traut** [comment]
nice! thanks
