### ISSUE TITLE
ERROR: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

### ISSUE THREAD

**Issue by CQRuu** [EclecticIQ/OpenTAXII#53]
Hi there!

I created a TAXII Server and used gunicorn as per the guide in http://www.opentaxii.org/en/stable/running.html. However, i'm receiving this error:

command: `taxii-poll --path https://<url>:<port>/services/poll --collection collection --username <username> --password <password> --port <port> --verify <path-to-my-ca-chain.cert.pem>`

> 2017-01-20 19:28:49,036 INFO: Polling using data binding: ALL
> 2017-01-20 19:28:49,045 INFO: Sending Poll_Request to https://\<url\>:\<port\>/services/poll
> 2017-01-20 19:28:50,163 ERROR: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

the poll only works if i used `--verify no` in my commands. Is there a way to let my self-signed certificate be verified?

**Comment by aukjan** [comment]
Hello @CQRuu,  thank you for your inquiry. 

One question for you, did you setup OpenTAXII to run behind SSL?  Are you using a reverse proxy. Can you give a little bit more information here? 

Thanks!

**Comment by guidovranken** [comment]
I didn't test this but this appears to be a generic SSL/TLS usage issue, and what you could do is create your own certificate authority and add its certificate to your trusted CA's, and then sign your server certificate with the CA. You also might want to look into TLS pre-shared key modes such as PSK and SRP.
