### ISSUE TITLE
SSL23_GET_SERVER_HELLO ERROR when stix connected to opentaxii

### ISSUE THREAD

**Issue by xiaochao** [EclecticIQ/OpenTAXII#54]
when i use stix server discover my opentaxii server. it shows error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol.

I run my opentaxii server follow the document http://www.opentaxii.org/en/stable/installation.html

My opentaxii version is 0.18

**Comment by traut** [comment]
@xiaochao OpenTAXII does not provide any SSL compatibilities, so if you have SSL configured, it is in your nginx/apache/etc

If you have no SSL configured, do not use `https://` schema in the Discovery URL

**Comment by xiaochao** [comment]
I do not use https:// Discovery URL.My discover URL is http://xxxxxxx/services/discovery-a
