### ISSUE TITLE
opentaxii.persistence.sqldb.SQLDatabaseAPI.get_service() incorrectly calls Service.get() instead of Service.query.get()

### ISSUE THREAD

**Issue by jwakefieldau** [EclecticIQ/OpenTAXII#56]
Found this when a unit test of mine failed with AttributeError:

<pre>
ret_se = SQLDatabaseAPI.get_service(self, service_id)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = &lt;(snipped) object at 0x7fe80d007ad0&gt;, service_id = 'test_cm_svc-A'

    def get_service(self, service_id):
>       return conv.to_service_entity(Service.get(service_id))
E       AttributeError: type object 'Service' has no attribute 'get'

../../../../../../../local/lib/python2.7/site-packages/opentaxii/persistence/sqldb/api.py:57: AttributeError
================================================================================================================== 1 failed, 3 passed in 0.53 seconds ==================================================================================================================
</pre>

**Comment by traut** [comment]
yep, it is a bug. Should be `Service.query.get(service_id)`. I wonder why it was not caught by unit tests
