### ISSUE TITLE
opentaxii.persistence.sqldb.SQLDatabaseAPI.update_service() unconditionally returns None instead of a ServiceEntity as probably intended

### ISSUE THREAD

**Issue by jwakefieldau** [EclecticIQ/OpenTAXII#57]
Also discovered by one of my unit tests.

The line https://github.com/EclecticIQ/OpenTAXII/blob/master/opentaxii/persistence/sqldb/api.py#L70 assigns the return value of `db.session.add()` to the local variable `service`.  However, the `.add()` method, having no `return` statement, implicitly returns `None`.  This means that `None` is unconditionally assigned to `service`, and `.update_service()` returns the return value of `return conv.to_service_entity(service)`, which in turn unconditionally returns `None` instead of a `ServiceEntity`.

The return value of `db.session.add()` should be ignored, which means `service` will still be bound to a `Service` object, and the subsequent call to `.to_service_entity()` will be able to return a `ServiceEntity` which will in turn be returned by `.update_service()`, which is almost certainly the intended behaviour.

**Comment by traut** [comment]
@jwakefieldau thanks! Looks like there are some gaps in the test coverage. I'll look through it as soon as I have time.

Will you be able to contribute the tests you wrote?

**Comment by jwakefieldau** [comment]
@traut Due to confidentiality / non-disclosure agreements with the client, I won't be able to contribute the test code, though I may be able to provide a description of the logic behind them.

**Comment by traut** [comment]
fixed in current master
