### ISSUE TITLE
Service FEED not available for OpenTAXII published sites

### ISSUE THREAD

**Issue by maxymax68** [EclecticIQ/OpenTAXII#60]
I am trying to access some data that was successfully pushed in the OpenTAXII server data collection. The said data can be retrieved with taxii-poll CLI, but this is failing if queried from an Anomali-STAXX server.

The error message is: "Service FEED not available for site https://domain:9000/services/discovery-a" while accessing via https://opentaxii.etlab.net:9000/services/discovery-a
 
And is "Service FEED not available for site http://opentaxii.etlab.net:9000/services/poll-a" while accessing via http://opentaxii.etlab.net:9000/services/poll-a

For reference, here is the CLI command used to push content into OpenTAXII:
taxii-push -f indicators.xml --path http://domain:9000/services/inbox-a --dest collection-A  
And here is the CLI command used to access the same data from OpenTAXII:
taxii-poll --path http://domain:9000/services/poll-a -c collection-A --username opentaxii --password test

Many thanks for your help.

**Comment by traut** [comment]
So you are able to pull content from OpenTAXII using Cabby but not from Anomali-STAXX?

**Comment by maxymax68** [comment]
yes this is the case.
I managed to get through it by disabling the https protocol from service definition. This is not an issue for the time being and I will looking into https options with gunicorn later.
The issue I now face is with the subcribtion-id that ise required from Anomali-STAXX for discovered collections. I can't find the right options of the taxii-subscription command. Do you have any example of that command I can start with? Many thanks.

**Comment by maxymax68** [comment]
I tried this:
$ taxii-subscription --host opentaxii.etlab.net --port 9000 --discovery discovery-a --path http://domain:9000/services/poll-a --username opentaxii --password test -a subscribe -c collection-B -s 1

And got:
2017-03-29 10:30:50,366 INFO: Sending Subscription_Management_Request to http://domain:9000/services/poll-a
2017-03-29 10:30:50,621 ERROR: FAILURE: Message not supported by this service

**Comment by traut** [comment]
@maxymax68 suscription calls are not supported by Poll Service. Collection Management service is responsible for subscription management

**Comment by maxymax68** [comment]
I can confirm it's working with collection management service.
Many thanks
