### ISSUE TITLE
poll data so slow when i pushed 5milion data to opentaxii

### ISSUE THREAD

**Issue by xiaochao** [EclecticIQ/OpenTAXII#76]
I think i need create mysql index.But i do not know which field the index create on.

**Comment by traut** [comment]
@xiaochao it might be that counting is slow. latest master allows you to disable counting in poll requests with a [`count_blocks_in_poll_responses`](https://github.com/EclecticIQ/OpenTAXII/blob/master/opentaxii/defaults.yml#L8) property
