### ISSUE TITLE
MySQL - (Probably) Schema issues causing feed corruption

### ISSUE THREAD

**Issue by FloatingGhost** [EclecticIQ/OpenTAXII#78]
Hoi there - just a quick and hopefully easy one here

I was trying to deploy OpenTAXII using MySQL as the backend, and found that content blocks and inbox messages get truncated to 64k, causing the feed to corrupt and crash any client that attempted to parse it.

Luckily I found out why - in the Persistence Database:
```sql
-> describe content_blocks;
+------------------+--------------+------+-----+---------+----------------+
| Field            | Type         | Null | Key | Default | Extra          |
+------------------+--------------+------+-----+---------+----------------+
| date_created     | datetime     | YES  |     | NULL    |                |
| id               | int(11)      | NO   | PRI | NULL    | auto_increment |
| message          | text         | YES  |     | NULL    |                |
| timestamp_label  | datetime     | YES  | MUL | NULL    |                |
| inbox_message_id | int(11)      | YES  | MUL | NULL    |                |
| content          | text         | YES  |     | NULL    |                |
| binding_id       | varchar(300) | YES  | MUL | NULL    |                |
| binding_subtype  | varchar(300) | YES  | MUL | NULL    |                |
+------------------+--------------+------+-----+---------+----------------+
```

`content` uses the `TEXT` type, which in MySQL is [Limited to 65535 bytes](http://boolean.co.nz/blog/max-length-for-mysql-text-field-types/135/) - apparently using `LONGTEXT` would fix it

I'd go PR it, but I'm not familiar with SqlAlchemy to not break anything else

Thanks :heart:

**Comment by aukjan** [comment]
Thanks for pointing out @FloatingGhost,  I will let @traut comment on this one after his vacation ;)

**Comment by traut** [comment]
`Text` in content fields is changed to SQLAlchemy's [`LargeBinary`](http://docs.sqlalchemy.org/en/latest/core/type_basics.html#sqlalchemy.types.LargeBinary)
