### ISSUE TITLE
content_blocks hex encoded

### ISSUE THREAD

**Issue by IW0DJC** [EclecticIQ/OpenTAXII#80]
hello, 
I got a opentaxii server based on a postgres db. Everything seems working fine but content_blocs/Content is hex-encoded. I pushed in a stix xml. Following the output of a taxii-poll :

(venv) ubuntu@taxiiserver:~$ taxii-poll --host 192.168.15.84 --port 9000 --path /services/poll --collection collection --username taxii --password taxii
2017-08-08 15:35:38,465 INFO: Polling using data binding: ALL
2017-08-08 15:35:38,468 INFO: Sending Poll_Request to http://192.168.15.84:9000/services/poll
\x3c737469783a535449585f5061636b61676520786d6c6e733a7873693d22687474703a2f2f7777772e77332e6f72672f323030312f584d4c536368656d612d696e7374616e63652220786d6c6e733a737469783d22687474703a2f2f737469782e6d697472652e6f72672f737469782d312220786d6c6e733a696e64696361746f723d22687474703a2f2f737469782e6d697472652e6f72672f496e64696361746f722d322220786d6c6e733a6379626f783d22687474703a2f2f6379626f782e6d697472652e6f72672f6379626f782d322220786d6c6e733a416464726573734f626a6563743d22687474703a2f2f6379626f782e6d697472652e6f72672f6f626a6563747323416464726573734f626a6563742d322220786d6c6e733a6379626f78566f636162733d22687474703a2f2f6379626f782e6d697472652e6f72672f64656661756c745f766f636162756c61726965732d322220786d6c6e733a73746978566f636162733d22687474703a2f2f737469782e6d697472652e6f72672f64656661756c745f766f636162756c61726965732d312220786d6c6e733a6578616d706c653d22687474703a2f2f6578616d706c652e636f6d2f2220786d6c6e733a74617869693d22687474703a2f2f74617869692e6d697472652e6f72672f6d657373616765732f74617869695f786d6c5f62696e64696e672d312220786d6c6e733a74617869695f31313d22687474703a2f2f74617869692e6d697472652e6f72672f6d657373616765732f74617869695f786d6c5f62696e64696e672d312e312220786d6c6e733a7464713d22687474703a2f2f74617869692e6d697472652e6f72672f71756572792f74617869695f64656661756c745f71756572792d3122207873693a736368656d614c6f636174696f6e3d222020202020687474703a2f2f737469782e6d697472652e6f72672f737469782d31202e2e2f737469785f636f72652e7873642020202020687474703a2f2f737469782e6d697472652e6f72672f496e64696361746f722d32202e2e2f696e64696361746f722e7873642020202020687474703a2f2f6379626f782e6d697472652e6f72672f64656661756c745f766f636162756c61726965732d32202e2e2f6379626f782f6379626f785f64656661756c745f766f636162756c61726965732e7873642020202020687474703a2f2f737469782e6d697472652e6f72672f64656661756c745f766f636162756c61726965732d31202e2e2f737469785f64656661756c745f766f636162756c61726965732e7873642020202020687474703a2f2f6379626f782e6d697472652e6f72672f6f626a6563747323416464726573734f626a6563742d32202e2e2f6379626f782f6f626a656374732f416464726573735f4f626a6563742e787364222069643d226578616d706c653a535449585061636b6167652d33336665336232322d303230312d343763662d383564302d393763303231363435323864222076657273696f6e3d22312e302e31223e0a202020203c737469783a535449585f4865616465723e0a20202020202020203c737469783a5469746c653e4578616d706c652077617463686c697374207468617420636f6e7461696e7320495020696e666f726d6174696f6e2e3c2f737469783a5469746c653e0a20202020202020203c737469783a5061636b6167655f496e74656e74207873693a747970653d2273746978566f636162733a5061636b616765496e74656e74566f6361622d312e30223e496e64696361746f7273202d2057617463686c6973743c2f737469783a5061636b6167655f496e74656e743e0a202020203c2f737469783a535449585f4865616465723e0a202020203c737469783a496e64696361746f72733e0a20202020202020203c737469783a496e64696361746f72207873693a747970653d22696e64696361746f723a496e64696361746f7254797065222069643d226578616d706c653a496e64696361746f722d33336665336232322d303230312d343763662d383564302d393763303231363435323864223e0a2020202020202020202020203c696e64696361746f723a54797065207873693a747970653d2273746978566f636162733a496e64696361746f7254797065566f6361622d312e30223e49502057617463686c6973743c2f696e64696361746f723a547970653e0a2020202020202020202020203c696e64696361746f723a4465736372697074696f6e3e53616d706c65204950204164647265737320496e64696361746f7220666f7220746869732077617463686c6973742e205468697320636f6e7461696e73206f6e6520696e64696361746f722077697468206120736574206f662074687265652049502061646472657373657320696e207468652077617463686c6973742e3c2f696e64696361746f723a4465736372697074696f6e3e0a2020202020202020202020203c696e64696361746f723a4f627365727661626c652069643d226578616d706c653a4f627365727661626c652d31633739383236322d613463642d343334642d613935382d383834643639383063343539223e0a202020202020202020202020202020203c6379626f783a4f626a6563742069643d226578616d706c653a4f626a6563742d31393830636534332d386530332d343930622d383633612d656134303464313232343265223e0a20202020202020202020202020202020202020203c6379626f783a50726f70657274696573207873693a747970653d22416464726573734f626a6563743a416464726573734f626a65637454797065222063617465676f72793d22697076342d61646472223e0a2020202020202020202020202020202020202020202020203c416464726573734f626a6563743a416464726573735f56616c756520636f6e646974696f6e3d22457175616c7322206170706c795f636f6e646974696f6e3d22414e59223e31302e302e302e302323636f6d6d61232331302e302e302e312323636f6d6d61232331302e302e302e323c2f416464726573734f626a6563743a416464726573735f56616c75653e0a20202020202020202020202020202020202020203c2f6379626f783a50726f706572746965733e0a202020202020202020202020202020203c2f6379626f783a4f626a6563743e0a2020202020202020202020203c2f696e64696361746f723a4f627365727661626c653e0a20202020202020203c2f737469783a496e64696361746f723e0a202020203c2f737469783a496e64696361746f72733e0a3c2f737469783a535449585f5061636b6167653e0a20202020
\x3c737469783a535449585f5061636b61676520786d6c6e733a7873693d22687474703a2f2f7777772e77332e6f72672f323030312f584d4c536368656d612d696e7374616e63652220786d6c6e733a737469783d22687474703a2f2f737469782e6d697472652e6f72672f737469782d312220786d6c6e733a696e64696361746f723d22687474703a2f2f737469782e6d697472652e6f72672f496e64696361746f722d322220786d6c6e733a6379626f783d22687474703a2f2f6379626f782e6d697472652e6f72672f6379626f782d322220786d6c6e733a416464726573734f626a6563743d22687474703a2f2f6379626f782e6d697472652e6f72672f6f626a6563747323416464726573734f626a6563742d322220786d6c6e733a6379626f78566f636162733d22687474703a2f2f6379626f782e6d697472652e6f72672f64656661756c745f766f636162756c61726965732d322220786d6c6e733a73746978566f636162733d22687474703a2f2f737469782e6d697472652e6f72672f64656661756c745f766f636162756c61726965732d312220786d6c6e733a6578616d706c653d22687474703a2f2f6578616d706c652e636f6d2f2220786d6c6e733a74617869693d22687474703a2f2f74617869692e6d697472652e6f72672f6d657373616765732f74617869695f786d6c5f62696e64696e672d312220786d6c6e733a74617869695f31313d22687474703a2f2f74617869692e6d697472652e6f72672f6d657373616765732f74617869695f786d6c5f62696e64696e672d312e312220786d6c6e733a7464713d22687474703a2f2f74617869692e6d697472652e6f72672f71756572792f74617869695f64656661756c745f71756572792d3122207873693a736368656d614c6f636174696f6e3d222020202020687474703a2f2f737469782e6d697472652e6f72672f737469782d31202e2e2f737469785f636f72652e7873642020202020687474703a2f2f737469782e6d697472652e6f72672f496e64696361746f722d32202e2e2f696e64696361746f722e7873642020202020687474703a2f2f6379626f782e6d697472652e6f72672f64656661756c745f766f636162756c61726965732d32202e2e2f6379626f782f6379626f785f64656661756c745f766f636162756c61726965732e7873642020202020687474703a2f2f737469782e6d697472652e6f72672f64656661756c745f766f636162756c61726965732d31202e2e2f737469785f64656661756c745f766f636162756c61726965732e7873642020202020687474703a2f2f6379626f782e6d697472652e6f72672f6f626a6563747323416464726573734f626a6563742d32202e2e2f6379626f782f6f626a656374732f416464726573735f4f626a6563742e787364222069643d226578616d706c653a535449585061636b6167652d33336665336232322d303230312d343763662d383564302d393763303231363435323864222076657273696f6e3d22312e302e31223e0a202020203c737469783a535449585f4865616465723e0a20202020202020203c737469783a5469746c653e4578616d706c652077617463686c697374207468617420636f6e7461696e7320495020696e666f726d6174696f6e2e3c2f737469783a5469746c653e0a20202020202020203c737469783a5061636b6167655f496e74656e74207873693a747970653d2273746978566f636162733a5061636b616765496e74656e74566f6361622d312e30223e496e64696361746f7273202d2057617463686c6973743c2f737469783a5061636b6167655f496e74656e743e0a202020203c2f737469783a535449585f4865616465723e0a202020203c737469783a496e64696361746f72733e0a20202020202020203c737469783a496e64696361746f72207873693a747970653d22696e64696361746f723a496e64696361746f7254797065222069643d226578616d706c653a496e64696361746f722d33336665336232322d303230312d343763662d383564302d393763303231363435323864223e0a2020202020202020202020203c696e64696361746f723a54797065207873693a747970653d2273746978566f636162733a496e64696361746f7254797065566f6361622d312e30223e49502057617463686c6973743c2f696e64696361746f723a547970653e0a2020202020202020202020203c696e64696361746f723a4465736372697074696f6e3e53616d706c65204950204164647265737320496e64696361746f7220666f7220746869732077617463686c6973742e205468697320636f6e7461696e73206f6e6520696e64696361746f722077697468206120736574206f662074687265652049502061646472657373657320696e207468652077617463686c6973742e3c2f696e64696361746f723a4465736372697074696f6e3e0a2020202020202020202020203c696e64696361746f723a4f627365727661626c652069643d226578616d706c653a4f627365727661626c652d31633739383236322d613463642d343334642d613935382d383834643639383063343539223e0a202020202020202020202020202020203c6379626f783a4f626a6563742069643d226578616d706c653a4f626a6563742d31393830636534332d386530332d343930622d383633612d656134303464313232343265223e0a20202020202020202020202020202020202020203c6379626f783a50726f70657274696573207873693a747970653d22416464726573734f626a6563743a416464726573734f626a65637454797065222063617465676f72793d22697076342d61646472223e0a2020202020202020202020202020202020202020202020203c416464726573734f626a6563743a416464726573735f56616c756520636f6e646974696f6e3d22457175616c7322206170706c795f636f6e646974696f6e3d22414e59223e31302e302e302e302323636f6d6d61232331302e302e302e312323636f6d6d61232331302e302e302e323c2f416464726573734f626a6563743a416464726573735f56616c75653e0a20202020202020202020202020202020202020203c2f6379626f783a50726f706572746965733e0a202020202020202020202020202020203c2f6379626f783a4f626a6563743e0a2020202020202020202020203c2f696e64696361746f723a4f627365727661626c653e0a20202020202020203c2f737469783a496e64696361746f723e0a202020203c2f737469783a496e64696361746f72733e0a3c2f737469783a535449585f5061636b6167653e0a20202020
2017-08-08 15:35:38,691 INFO: 2 blocks polled

**Comment by traut** [comment]
@IW0DJC thanks for reporting, I'll take a look. 

This is unusual behaviour. Did you use default sqldb Persistence API implementation?

**Comment by IW0DJC** [comment]
Hello, thank you for your answer. Simply, I changed config.yml in order to use postgresql. Everything works but the content is binascii encoded. Then, i revert to SQLite Simply changing connection Param's in config.yml and everything works ...RegardsFrancescoIl 11 ago 2017 13:46, Sergey Polzunov <notifications@github.com> ha scritto:@IW0DJC thanks for reporting, I'll take a look.
This is unusual behaviour. Did you use default sqldb Persistence API implementation?

**Comment by traut** [comment]
@IW0DJC I suspect this is because of incorrect field type in ContentBlock model in default SQLDB implementation of persistence api. I'm talking about this:
```python
    content = schema.Column(types.Text)
```
in [models.py](https://github.com/EclecticIQ/OpenTAXII/blob/master/opentaxii/persistence/sqldb/models.py#L51).

Obviously, content block content is binary and should not be stored as text in the database.

**Comment by traut** [comment]
fixed by changing `Text` to `LargeBinary`
