### ISSUE TITLE
Client certificate authentication - unauthorized

### ISSUE THREAD

**Issue by imereau** [EclecticIQ/OpenTAXII#83]
Dears,

I am trying to authenticate towards my TAXII server using a client certificate + key file. The gunicorn server is started with the ca-certs that signed my client certificate.
Server certificate is well validated by the client, but the other way round, I can't get opentaxii to validate the user certificate:

taxii-poll --path https://taxi.local.test:9000/services/poll --collection collection --cert /tmp/client.crt --key /tmp/client.key

ERROR: UNAUTHORIZED

I get the same response back if I am using the cabby python library.
username / password authentication works fine thou, but it is not a possible option for me.

Is it enough to have the client cert signed by a trusted ca or is there any other setup to be done (i.e. define the clients CN's somewhere in config e.g.)?

Pardon me if the question has been answered already or if it is documented somewhere, but I couldn't find it.

many thanks in advance for your help!

BR's
irving

**Comment by imereau** [comment]
Hello,

Yes, indeed, the client validates well the server certificate. It trustes the CA that signed the server cert and all is ok from that point of view.
Regarding the client certificate, it's gunicorn validating the cert indeed, but I am wondering if there is a second layer of authentication within opentaxii based e.g. on the CN. I actually do not provide any other credentials; I think SSL-only authentication, without additional username/password is an option (as described at http://cabby.readthedocs.io/en/stable/user.html). Am I misunderstnading something?

Thx a lot again.
Irving

**Comment by traut** [comment]
no, OpenTAXII does not do any certificate-based authentication by default (if you're using default Auth API). You can implement it, if you want, in your custom auth api.

I'll see how can I make docs clearer on that

**Comment by imereau** [comment]
alright, thanks for the answer, appreciate it.
Just to be sure, do I understand correctly that the last authentication method described below (taken from http://cabby.readthedocs.io/en/stable/user.html) relies on a custom implementation of the auth api?
Thanks a lot again!

Authentication methods
It is possible to set authentication parameters for TAXII requests:

from cabby import create_client

client = create_client(
    'secure.taxiiserver.com',
    discovery_path='/services/discovery')

# basic authentication
client.set_auth(username='john', password='p4ssw0rd')

# or JWT based authentication
client.set_auth(
    username='john',
    password='p4ssw0rd',
    jwt_auth_url='/management/auth'
)

# or basic authentication with SSL
client.set_auth(
    username='john',
    password='p4ssw0rd',
    cert_file='/keys/ssl.cert',
    key_file='/keys/ssl.key'
)

# or only SSL authentication
client.set_auth(
    cert_file='/keys/ssl.cert',
    key_file='/keys/ssl.key'
)

**Comment by traut** [comment]
> do I understand correctly that the last authentication method described below (taken from http://cabby.readthedocs.io/en/stable/user.html) relies on a custom implementation of the auth api?

no, this latest example has a wrong comment. SSL there is not for authentication but for the protocol security

**Comment by imereau** [comment]
ok, thank you, understood!

BR's
Irving
