### ISSUE TITLE
Collection not found, but also can't be created

### ISSUE THREAD

**Issue by arcsector** [EclecticIQ/OpenTAXII#84]
Hello there EclecticIQ,

First off let me say this is a fantastic product and I can't wait to see how it develops. I do, however have a bit of a problem.

I'm using cabby in conjunction with opentaxii as suggested, but I am using MySQL instead of PostGRE. I created my services without a problem with `opentaxii-create-services -c` and I created my collections the first time without a problem as well with `opentaxii-create-collections -c`. However, when i use cabby's `taxii-push` to push items to the collection I have, it doesn't work, throwing the following error:
```
674 ERROR: NOT_FOUND: ITEM=taxiistand; The Data Collection was not found
```
Next, when I go to my collections and try to recreate them with `opentaxii-create-collections -c collections.yaml`, the command throws the following error:
```
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: data_collections.name [SQL: 'INSERT INTO data_collections (date_created, name, type, description, accept_all_content, bindings, available, volume) VALUES (?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: ('2017-09-28 16:29:49.880883', 'taxiistand', 'DATA_SET', None, 1, '[]', 1, 0)
```
I'm not quite sure what to do. Thanks for all your help! I'll be attaching my collections.yaml and services.yaml as well

[services.txt](https://github.com/EclecticIQ/OpenTAXII/files/1341669/services.txt)
[collections.txt](https://github.com/EclecticIQ/OpenTAXII/files/1341668/collections.txt)

**Comment by traut** [comment]
hey @arcsector. Sorry for the delay with the reply. The first error tells you that collection `taxiistand` does not exist:
```
674 ERROR: NOT_FOUND: ITEM=taxiistand; The Data Collection was not found
```
This looks like an incorrect collection name. Are you sure you have correct parameters in your `taxii-push` command?

As about second error, OpenTAXII does not support management of collection/services at the moment. So the only command is to create them. Obviously, if you try creating the same collection twice, you will get error like you got -- `UNIQUE constraint failed: data_collections.name` -- meaning, "collection with this name already exists"

**Comment by arcsector** [comment]
Alright, I didn't recognize that there was no feature for editing collections/replacing them yet. Thank you for your help. Are there plans for just adding single collections in the future? Or replacing other collections?

**Comment by traut** [comment]
@arcsector current master has the ability to sync data configuration ([like this](https://github.com/EclecticIQ/OpenTAXII/blob/master/examples/data-configuration.yml)) with CLI command `opentaxii-sync-data`). Documentation is still missing though

**Comment by arcsector** [comment]
Awesome. Thanks so much for the note! Is the documentation going to be updated with this information and/or the arguments that the collections and services yml accepts?

Again, fantastic service. I was just curious if there were any plans.

**Comment by traut** [comment]
sure, I'll update documentation with the details. In the meantime, please see variety of service/collection/account parameters in [the example I added](https://github.com/EclecticIQ/OpenTAXII/blob/master/examples/data-configuration.yml).

**Comment by arcsector** [comment]
You're fantastic. Thank you so much. I'm wondering if there's a way I can help you add a feature to dedup collections.
