### ISSUE TITLE
How could I use my own XSD to verify the XML(stix)？

### ISSUE THREAD

**Issue by p0561199** [eclecticiq/OpenTAXII#85]
I need to use the particular XSD to verify the XML, but I can not change the XSD to replace the TAXII_XMLMessageBinding_Schema_11.xsd ? T_T How to do Q_Q?

**Comment by traut** [comment]
hey @p0561199. unfortunately it is not something you can easily extend.

opentaxii uses schema validators from [libtaxii](https://github.com/TAXIIProject/libtaxii) project to validate TAXII XML. It does unpack embedded XML, like STIX (unfortunately) but this is more of a side effect. No validation of content is supported yet

**Comment by arcsector** [comment]
@p0561199 If this is still an issue, I might give this a shot using the [stix-validator](https://stix-validator.readthedocs.io/en/stable/examples/schema.html#using-non-bundled-schemas). Question:

Do you want this on a per-collection basis or on a per-instance basis (only files going to a certain collection should be validated vs all files ingested by that instance of opentaxii)?

**Comment by eric-eclecticiq** [comment]
We have recently made a decision to consider this project feature-complete. It means we still maintain it, however we focus only on bug fixes. As this issue is a feature request, unfortunately we won’t add it and therefore I’m closing this issue.
