### ISSUE TITLE
Curl to /management/auth broken

### ISSUE THREAD

**Issue by arcsector** [EclecticIQ/OpenTAXII#88]
Hello guys,

I'm curling with the following command:
<pre><code>curl -v -H "Content-Type: application/json" -X POST -d '{"username":"admin","password":"pass"}' http://localhost:9000/management/auth></code></pre>

Where `admin` and `pass` are the details specified in the `accounts` section of the `OPENTAXII_CONFIG` file. However I'm getting back this output:
<pre><code>*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 9000 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 9000 (#0)
< POST /management/auth HTTP/1.1
< Host: localhost:9000
< User-Agent: curl/7.52.1
< Accept: */*
< Content-Type: application/json
< Content-Length: 39
<
* upload completely sent off: 39 out of 39 bytes
127.0.0.1 - - [19/Oct/2017 10:20:33] "POST /management/auth HTTP/1.1" 401 -
* HTTP 1.0, assume close after body
< HTTP/1.0 401 UNAUTHORIZED
< Content-Type: text/html
< Content-Length: 339
< Server: Werkzeug/0.12.2 Python/2.7.13
< Date: Thu, 19 Oct 2017 17:20:33 GMT
<

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>401 Unauthorized</title>
<h1>Unauthorized</h1>
<p>The server could not verify that you are authorized to access the URL requested.  You either supplied the wrong credentials (e.g. a bad password), or your browser doesn't understand how to supply the credentials required.</p>
* Curl_http_done: called premature == 0
* Closing connection 0</code></pre>

I'm curious if this is a working bug, or if auth via json token is being deprecated. 

Thank you guys!

**Comment by traut** [comment]
@arcsector hey! did you sync accounts from the config file into DB?

**Comment by arcsector** [comment]
Ah; i think this was when you rolled out the new commits and I didn't know about the opentaxii-sync-data function, so my sqlite database was uninitialized. I'll close it.
