### ISSUE TITLE
docker won't start up

### ISSUE THREAD

**Issue by RomanFire1** [eclecticiq/OpenTAXII#91]
docker won't start up the image and keeps giving me this error:
```
6b4710cb13f6c87571d9fcd9dc37105e316209e8e5ae09847ef0cf90060b0a53
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:334: running prestart hook 0 caused \\\"fork/exec /usr/bin/dockerd (deleted): no such file or directory\\\"\"\n".
```

**Comment by arcsector** [comment]
Try updating and/or restarting the docker service. Also (obviously) make sure /usr/bin/dockerd exists. People [here](https://github.com/moby/moby/issues/29640) said that worked for them.

**Comment by traut** [comment]
@RomanFire1 did that last advice from @arcsector helper you?
