### ISSUE TITLE
[Enhancement] Public/Private Key Authentication

### ISSUE THREAD

**Issue by arcsector** [EclecticIQ/OpenTAXII#94]
Hi there, I think a useful feature would be the allowing of public/private key authentication through something like pycrypto. This would allow service accounts to automatically poll data while still authenticating with the server without the need to store a username/password, which is unethical.

**Comment by traut** [comment]
I'm a bit reluctant to add this logic into OpenTAXII itself. It seems to me that web server, that is required in order to run OpenTAXII in production, should take care of SSL-based access control and possibly authentication

**Comment by arcsector** [comment]
You're right. I'll close this.
