### ISSUE TITLE
Qradar is not able to recognize the collections

### ISSUE THREAD

**Issue by mcamachotw** [EclecticIQ/OpenTAXII#96]
I saw a thread that talks about Qradar is not able to recognize the collections, even though the server opentaxii is up and running, but I did not see how they solved it, I have exactly the same problem @traut check with another participant, could you please share how they solved what Qradar can read the collections I have on my own server opentaxii, I also change from data_set to data_feed but it still does not work. first of all, Thanks.

**Comment by traut** [comment]
I'm closing this as a duplicate for #55. Please leave a comment there to keep context in one issue
