### ISSUE TITLE
Outdated PyPi package

### ISSUE THREAD

**Issue by dhkron** [eclecticiq/OpenTAXII#97]
Hello!

I've noticed that the Opentaxii in PyPi is quite outdated (https://pypi.python.org/pypi/opentaxii/), so much as 8 month ago.
Could you please redeploy it?

Thanks!

**Comment by traut** [comment]
@dhkron the latest code packs some changes that need to be reflected in the docs, that's why the delay. I'm planning on making necessary changes and releasing new version in the coming weeks

**Comment by traut** [comment]
new [release 0.1.10](https://github.com/eclecticiq/OpenTAXII/releases/tag/0.1.10) is published.
